spring.application.name=stock_market_service

# Enable the H2 Console
# Spring will use these env variables which we will set in Docker
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# This ensures Hibernate creates the tables in Postgres automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect